/**
 * registry.ts — GENERATED. Do not edit by hand.
 *
 * Run `npm run gen:registry` after adding a page. Each page declares its own
 * route with an `@route` tag in its header; this file is derived from those
 * declarations so that no two feature authors ever write the same file (an
 * earlier hand-maintained version lost 30+ registrations to concurrent edits).
 *
 * Anything absent here renders <PageStub> from the route manifest metadata, so
 * the route always exists, is deep-linkable, and never 404s mid-build.
 *
 * 188 of 191 routes are built.
 */
import type { ComponentType, LazyExoticComponent } from "react";

export type PageModule = { default: ComponentType };
export type PageLoader = () => Promise<PageModule>;

/** path → dynamic import of the page module. */
export const PAGE_REGISTRY: Readonly<Record<string, PageLoader>> = {
  "/admin": () => import("./admin/pages/CommandCentre.page"),
  "/admin/alerts": () => import("./admin/pages/AlertFeed.page"),
  "/admin/analytics": () => import("./admin/pages/AnalyticsHome.page"),
  "/admin/analytics/ai": () => import("./admin/pages/AnalyticsAi.page"),
  "/admin/analytics/attendance": () => import("./admin/pages/AnalyticsAttendance.page"),
  "/admin/analytics/builder": () => import("./admin/pages/ReportBuilder.page"),
  "/admin/analytics/compliance": () => import("./admin/pages/AnalyticsCompliance.page"),
  "/admin/analytics/employees": () => import("./admin/pages/AnalyticsEmployees.page"),
  "/admin/analytics/employees/:employeeCode": () => import("./admin/pages/AnalyticsEmployeeDetail.page"),
  "/admin/analytics/exports": () => import("./admin/pages/AnalyticsExports.page"),
  "/admin/analytics/kiosk": () => import("./admin/pages/AnalyticsKiosk.page"),
  "/admin/analytics/leave": () => import("./admin/pages/AnalyticsLeave.page"),
  "/admin/analytics/metrics": () => import("./admin/pages/AnalyticsMetrics.page"),
  "/admin/analytics/payroll": () => import("./admin/pages/AnalyticsPayroll.page"),
  "/admin/analytics/scheduled": () => import("./admin/pages/AnalyticsScheduled.page"),
  "/admin/analytics/workforce": () => import("./admin/pages/AnalyticsWorkforce.page"),
  "/admin/assets/allocations": () => import("./admin/pages/AssetAllocations.page"),
  "/admin/assets/consumables": () => import("./admin/pages/AssetConsumables.page"),
  "/admin/assets/exit-liability": () => import("./admin/pages/AssetExitLiability.page"),
  "/admin/assets/history": () => import("./admin/pages/AssetHistory.page"),
  "/admin/assets/master": () => import("./admin/pages/AssetMaster.page"),
  "/admin/assets/returns": () => import("./admin/pages/AssetReturns.page"),
  "/admin/attendance/bulk": () => import("./admin/pages/BulkActions.page"),
  "/admin/attendance/coverage": () => import("./admin/pages/EventCoverage.page"),
  "/admin/attendance/days": () => import("./admin/pages/DayRecords.page"),
  "/admin/attendance/exceptions": () => import("./admin/pages/AttendanceExceptions.page"),
  "/admin/attendance/live": () => import("./admin/pages/LiveBoard.page"),
  "/admin/attendance/locks": () => import("./admin/pages/PeriodLocks.page"),
  "/admin/attendance/punches": () => import("./admin/pages/PunchLog.page"),
  "/admin/attendance/punches/new": () => import("./admin/pages/ManualPunch.page"),
  "/admin/attendance/recompute": () => import("./admin/pages/RecomputeConsole.page"),
  "/admin/attendance/regularisations": () => import("./admin/pages/Regularisations.page"),
  "/admin/attendance/roster": () => import("./admin/pages/RosterPlanner.page"),
  "/admin/audit": () => import("./admin/pages/AuditTimeline.page"),
  "/admin/audit/data-access": () => import("./admin/pages/AuditDataAccess.page"),
  "/admin/audit/diff/:eventId": () => import("./admin/pages/AuditDiff.page"),
  "/admin/audit/entity/:type/:id": () => import("./admin/pages/AuditEntityHistory.page"),
  "/admin/audit/exports": () => import("./admin/pages/AuditExports.page"),
  "/admin/audit/integrity": () => import("./admin/pages/AuditIntegrity.page"),
  "/admin/audit/sessions": () => import("./admin/pages/AuditSessions.page"),
  "/admin/audit/user/:userId": () => import("./admin/pages/AuditUserTrail.page"),
  "/admin/comms/acknowledgements": () => import("./admin/pages/Acknowledgements.page"),
  "/admin/comms/announcements": () => import("./admin/pages/Announcements.page"),
  "/admin/comms/broadcasts": () => import("./admin/pages/Broadcasts.page"),
  "/admin/comms/delivery": () => import("./admin/pages/DeliveryLog.page"),
  "/admin/comms/helpdesk": () => import("./admin/pages/Helpdesk.page"),
  "/admin/comms/policies": () => import("./admin/pages/PolicyPublication.page"),
  "/admin/comms/templates": () => import("./admin/pages/CommsTemplates.page"),
  "/admin/documents/access-log": () => import("./admin/pages/DocumentAccessLog.page"),
  "/admin/documents/esign": () => import("./admin/pages/DocumentEsign.page"),
  "/admin/documents/expiry": () => import("./admin/pages/DocumentExpiry.page"),
  "/admin/documents/generate": () => import("./admin/pages/DocumentGenerate.page"),
  "/admin/documents/pending": () => import("./admin/pages/DocumentPending.page"),
  "/admin/documents/repository": () => import("./admin/pages/DocumentRepository.page"),
  "/admin/documents/templates": () => import("./admin/pages/DocumentTemplates.page"),
  "/admin/documents/types": () => import("./admin/pages/DocumentTypes.page"),
  "/admin/kiosk/abuse": () => import("./admin/pages/KioskAbuse.page"),
  "/admin/kiosk/consent": () => import("./admin/pages/ConsentRegister.page"),
  "/admin/kiosk/devices": () => import("./admin/pages/KioskDevices.page"),
  "/admin/kiosk/enrolment": () => import("./admin/pages/EnrolmentQueue.page"),
  "/admin/kiosk/match-review": () => import("./admin/pages/MatchReview.page"),
  "/admin/kiosk/operators": () => import("./admin/pages/KioskOperators.page"),
  "/admin/kiosk/policy": () => import("./admin/pages/KioskPolicy.page"),
  "/admin/kiosk/purge": () => import("./admin/pages/TemplatePurge.page"),
  "/admin/kiosk/templates": () => import("./admin/pages/FaceTemplates.page"),
  "/admin/leave/apply": () => import("./admin/pages/LeaveOnBehalf.page"),
  "/admin/leave/adjustments": () => import("./admin/pages/LeaveAdjustments.page"),
  "/admin/leave/balances": () => import("./admin/pages/LeaveBalances.page"),
  "/admin/leave/calendar": () => import("./admin/pages/OrgLeaveCalendar.page"),
  "/admin/leave/comp-off": () => import("./admin/pages/CompOffLedger.page"),
  "/admin/leave/encashment": () => import("./admin/pages/LeaveEncashment.page"),
  "/admin/leave/ledger/:code": () => import("./admin/pages/LeaveLedger.page"),
  "/admin/leave/requests": () => import("./admin/pages/LeaveRequests.page"),
  "/admin/leave/rollover": () => import("./admin/pages/LeaveRollover.page"),
  "/admin/leave/types": () => import("./admin/pages/LeaveTypes.page"),
  "/admin/org/chart": () => import("./admin/pages/OrgChart.page"),
  "/admin/org/cost-centres": () => import("./admin/pages/CostCentres.page"),
  "/admin/org/custom-fields": () => import("./admin/pages/CustomFields.page"),
  "/admin/org/departments": () => import("./admin/pages/Departments.page"),
  "/admin/org/designations": () => import("./admin/pages/Designations.page"),
  "/admin/org/entities": () => import("./admin/pages/Entities.page"),
  "/admin/org/grades": () => import("./admin/pages/Grades.page"),
  "/admin/org/locations": () => import("./admin/pages/Locations.page"),
  "/admin/org/sections": () => import("./admin/pages/Sections.page"),
  "/admin/payroll/arrears": () => import("./admin/pages/PayrollArrears.page"),
  "/admin/payroll/bank-advice": () => import("./admin/pages/PayrollBankAdvice.page"),
  "/admin/payroll/compensation": () => import("./admin/pages/Compensation.page"),
  "/admin/payroll/components": () => import("./admin/pages/SalaryComponents.page"),
  "/admin/payroll/form16": () => import("./admin/pages/PayrollForm16.page"),
  "/admin/payroll/overtime": () => import("./admin/pages/PayrollOvertime.page"),
  "/admin/payroll/payslips": () => import("./admin/pages/PayslipRegister.page"),
  "/admin/payroll/register": () => import("./admin/pages/WageRegister.page"),
  "/admin/payroll/reimbursements": () => import("./admin/pages/PayrollReimbursements.page"),
  "/admin/payroll/revisions": () => import("./admin/pages/SalaryRevisions.page"),
  "/admin/payroll/runs": () => import("./admin/pages/PayrollRuns.page"),
  "/admin/payroll/runs/:id": () => import("./admin/pages/PayrollRunDetail.page"),
  "/admin/payroll/statutory": () => import("./admin/pages/PayrollStatutory.page"),
  "/admin/payroll/structures": () => import("./admin/pages/SalaryStructures.page"),
  "/admin/payroll/variance": () => import("./admin/pages/PayrollVariance.page"),
  "/admin/people": () => import("./admin/pages/Directory.page"),
  "/admin/people/:code": () => import("./admin/pages/Employee360.page"),
  "/admin/people/:code/attendance": () => import("./admin/pages/EmployeeAttendance.page"),
  "/admin/people/:code/audit": () => import("./admin/pages/EmployeeAudit.page"),
  "/admin/people/:code/compensation": () => import("./admin/pages/EmployeeCompensation.page"),
  "/admin/people/archive": () => import("./admin/pages/PeopleArchive.page"),
  "/admin/people/changes": () => import("./admin/pages/ChangeRequests.page"),
  "/admin/people/exits": () => import("./admin/pages/Exits.page"),
  "/admin/people/import": () => import("./admin/pages/BulkImport.page"),
  "/admin/people/lifecycle": () => import("./admin/pages/Lifecycle.page"),
  "/admin/people/new": () => import("./admin/pages/AddEmployee.page"),
  "/admin/people/onboarding": () => import("./admin/pages/Onboarding.page"),
  "/admin/people/rehire": () => import("./admin/pages/Rehire.page"),
  "/admin/people/transfers": () => import("./admin/pages/Transfers.page"),
  "/admin/settings/ai": () => import("./admin/pages/AiConfiguration.page"),
  "/admin/settings/api": () => import("./admin/pages/ApiKeys.page"),
  "/admin/settings/backup": () => import("./admin/pages/BackupRetention.page"),
  "/admin/settings/branding": () => import("./admin/pages/Branding.page"),
  "/admin/settings/flags": () => import("./admin/pages/FeatureFlags.page"),
  "/admin/settings/health": () => import("./admin/pages/SystemHealth.page"),
  "/admin/settings/integrations": () => import("./admin/pages/Integrations.page"),
  "/admin/settings/localisation": () => import("./admin/pages/Localisation.page"),
  "/admin/settings/notifications": () => import("./admin/pages/NotificationTemplates.page"),
  "/admin/settings/roles": () => import("./admin/pages/Roles.page"),
  "/admin/settings/security": () => import("./admin/pages/SecuritySettings.page"),
  "/admin/tasks": () => import("./admin/pages/AdminTasks.page"),
  "/admin/time/assignments": () => import("./admin/pages/PolicyAssignments.page"),
  "/admin/time/attendance-policies": () => import("./admin/pages/AttendancePolicies.page"),
  "/admin/time/holidays": () => import("./admin/pages/Holidays.page"),
  "/admin/time/pay-periods": () => import("./admin/pages/PayPeriods.page"),
  "/admin/time/resolver": () => import("./admin/pages/PolicyResolver.page"),
  "/admin/time/shifts": () => import("./admin/pages/Shifts.page"),
  "/admin/time/weekly-offs": () => import("./admin/pages/WeeklyOffs.page"),
  "/admin/workflow/delegations": () => import("./admin/pages/Delegations.page"),
  "/admin/workflow/designer": () => import("./admin/pages/WorkflowDesigner.page"),
  "/admin/workflow/inbox": () => import("./admin/pages/ApprovalInbox.page"),
  "/admin/workflow/overrides": () => import("./admin/pages/OverrideLog.page"),
  "/admin/workflow/sla": () => import("./admin/pages/SlaEscalations.page"),
  "/me": () => import("./home/pages/Home.page"),
  "/me/activity": () => import("./settings/pages/MyActivity.page"),
  "/me/apply": () => import("./apply/pages/ApplyLauncher.page"),
  "/me/apply/asset": () => import("./apply/pages/AssetRequest.page"),
  "/me/apply/certification": () => import("./apply/pages/CertificationClaim.page"),
  "/me/apply/claim": () => import("./apply/pages/LocalClaim.page"),
  "/me/apply/resignation": () => import("./apply/pages/Resignation.page"),
  "/me/apply/tax": () => import("./apply/pages/IncomeTax.page"),
  "/me/apply/travel": () => import("./apply/pages/TravelRequisition.page"),
  "/me/apply/web-punch": () => import("./apply/pages/WebPunchRequest.page"),
  "/me/approvals": () => import("./approvals/pages/Approvals.page"),
  "/me/ask": () => import("./ai/pages/Ask.page"),
  "/me/ask/history": () => import("./ai/pages/Conversations.page"),
  "/me/assets": () => import("./assets/pages/MyAssets.page"),
  "/me/attendance": () => import("./attendance/pages/MyAttendance.page"),
  "/me/attendance/:date": () => import("./attendance/pages/AttendanceDayDetail.page"),
  "/me/comp-off": () => import("./leave/pages/CompOff.page"),
  "/me/helpdesk": () => import("./helpdesk/pages/Helpdesk.page"),
  "/me/helpdesk/:id": () => import("./helpdesk/pages/Ticket.page"),
  "/me/holidays": () => import("./holidays/pages/Holidays.page"),
  "/me/leave": () => import("./leave/pages/MyLeave.page"),
  "/me/leave/:id": () => import("./leave/pages/LeaveDetail.page"),
  "/me/leave/apply": () => import("./leave/pages/LeaveApply.page"),
  "/me/leave/calendar": () => import("./leave/pages/LeaveCalendar.page"),
  "/me/notifications": () => import("./notifications/pages/Notifications.page"),
  "/me/payslips": () => import("./pay/pages/MyPayslips.page"),
  "/me/payslips/:period": () => import("./pay/pages/PayslipViewer.page"),
  "/me/policies": () => import("./policies/pages/Policies.page"),
  "/me/policies/:slug": () => import("./policies/pages/PolicyReader.page"),
  "/me/profile/basic": () => import("./profile/pages/ProfileBasic.page"),
  "/me/profile/custom": () => import("./profile/pages/ProfileCustom.page"),
  "/me/documents": () => import("./docs/pages/MyDocuments.page"),
  "/me/profile/documents": () => import("./profile/pages/ProfileDocuments.page"),
  "/me/profile/employment": () => import("./profile/pages/ProfileEmployment.page"),
  "/me/profile/history": () => import("./profile/pages/ProfileHistory.page"),
  "/me/profile/payment": () => import("./profile/pages/ProfilePayment.page"),
  "/me/profile/personal": () => import("./profile/pages/ProfilePersonal.page"),
  "/me/profile/salary": () => import("./pay/pages/MySalary.page"),
  "/me/regularizations": () => import("./attendance/pages/MyRegularizations.page"),
  "/me/regularizations/new": () => import("./attendance/pages/NewRegularization.page"),
  "/me/settings": () => import("./settings/pages/SettingsIndex.page"),
  "/me/settings/notifications": () => import("./settings/pages/NotificationPreferences.page"),
  "/me/settings/security": () => import("./settings/pages/Security.page"),
  "/team": () => import("./team/pages/TeamToday.page"),
  "/team/analytics": () => import("./team/pages/TeamAnalytics.page"),
  "/team/approvals": () => import("./team/pages/TeamApprovals.page"),
  "/team/attendance": () => import("./team/pages/TeamAttendance.page"),
  "/team/leave": () => import("./team/pages/TeamLeave.page"),
  "/team/people": () => import("./team/pages/TeamPeople.page"),
  "/team/people/:employeeCode": () => import("./team/pages/ReporteeProfile.page"),
  "/team/performance": () => import("./team/pages/TeamPerformance.page"),
  "/team/roster": () => import("./team/pages/TeamRoster.page"),
};

/** Populated at runtime by the router; exported for tests. */
export type LazyPage = LazyExoticComponent<ComponentType>;
