/**
 * Route-tree invariants (spec-architecture D-06). These run on every PR and are
 * the mechanised version of "no screen ships without an access decision".
 */
import { readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { PUBLIC_PATHS, REDIRECTS, ROUTES } from "./route-manifest";
import { PAGE_REGISTRY } from "@/features/registry";

describe("route manifest", () => {
  it("declares a capability for every authenticated route", () => {
    const missing = ROUTES.filter((r) => !r.cap);
    expect(missing.map((r) => r.path)).toEqual([]);
  });

  it("has no duplicate paths", () => {
    const seen = new Map<string, number>();
    for (const r of ROUTES) seen.set(r.path, (seen.get(r.path) ?? 0) + 1);
    const dupes = [...seen.entries()].filter(([, n]) => n > 1).map(([p]) => p);
    expect(dupes).toEqual([]);
  });

  it("uses absolute paths and never collides with a public path", () => {
    for (const r of ROUTES) {
      expect(r.path.startsWith("/")).toBe(true);
      expect(PUBLIC_PATHS as readonly string[]).not.toContain(r.path);
    }
  });

  it("gives every route a title and an actionable hint", () => {
    for (const r of ROUTES) {
      expect(r.title.length).toBeGreaterThan(2);
      // The hint is what the stub shows; a bare placeholder is not acceptable.
      expect(r.hint.length).toBeGreaterThan(15);
      expect(r.hint).not.toMatch(/TODO|TBD|coming soon/i);
    }
  });

  it("scopes /me, /team and /admin to the right capability tier", () => {
    for (const r of ROUTES) {
      if (r.path.startsWith("/me")) expect(r.cap).toBe("me.view");
      if (r.path.startsWith("/team")) expect(r.cap).toBe("team.view");
      if (r.path.startsWith("/admin")) expect(["admin.access", "admin.super"]).toContain(r.cap);
    }
  });

  it("only registers pages for paths that exist in the manifest", () => {
    const paths = new Set(ROUTES.map((r) => r.path));
    for (const registered of Object.keys(PAGE_REGISTRY)) {
      expect(paths.has(registered)).toBe(true);
    }
  });

  /**
   * The reverse direction, and the one that actually bit us. The test above
   * catches a registration pointing at no route; this catches a page file that
   * nothing registers — a screen sitting finished on disk while the user sees
   * <PageStub>. It happened at scale: registry.ts was hand-appended by several
   * authors at once, each wrote the whole file, and the last writer silently
   * dropped 30+ registrations. Nothing failed, no error was logged, and routes
   * that had worked simply went back to being placeholders.
   *
   * registry.ts is now generated by scripts/gen-registry.mjs from the `@route`
   * tag in each page's header. This test is the guard that it was re-run.
   */
  it("registers every page file that exists on disk", () => {
    // Vitest rewrites import.meta.url to a non-file scheme, so resolve from the
    // project root instead — vitest always runs with cwd at the package root.
    const featuresDir = join(process.cwd(), "src/features");
    const pages: string[] = [];
    const walk = (dir: string): void => {
      for (const entry of readdirSync(dir, { withFileTypes: true })) {
        const full = join(dir, entry.name);
        if (entry.isDirectory()) walk(full);
        else if (entry.name.endsWith(".page.tsx")) pages.push(full);
      }
    };
    walk(featuresDir);

    // Sanity: if the walk finds nothing the assertion below is vacuous.
    expect(pages.length).toBeGreaterThan(20);

    const registeredModules = new Set(
      Object.keys(PAGE_REGISTRY).map((path) => path),
    );
    expect(registeredModules.size).toBeGreaterThan(0);

    const unregistered = pages.filter((file) => {
      const src = readFileSync(file, "utf8");
      // Pages the router mounts itself opt out explicitly and on purpose.
      if (/@route-standalone\s+\//.test(src)) return false;
      const tag = /@route\s+(\/\S+)/.exec(src);
      // No tag at all is a failure too: gen-registry cannot place it.
      if (!tag?.[1]) return true;
      return !Object.prototype.hasOwnProperty.call(PAGE_REGISTRY, tag[1]);
    });

    expect(
      unregistered.map((f) => f.slice(f.indexOf("/features/"))),
      "page files present but not in PAGE_REGISTRY — run `npm run gen:registry`",
    ).toEqual([]);
  });

  it("points every redirect at a real destination", () => {
    const paths = new Set<string>([...ROUTES.map((r) => r.path), ...PUBLIC_PATHS]);
    for (const r of REDIRECTS) {
      expect(paths.has(r.to)).toBe(true);
    }
  });

  it("covers the spec's headline surfaces", () => {
    const paths = ROUTES.map((r) => r.path);
    // Spot-checks: the four surfaces and the load-bearing screens.
    for (const required of [
      "/me",
      "/me/attendance",
      "/me/attendance/:date",
      "/me/leave/apply",
      "/me/payslips",
      "/team",
      "/team/approvals",
      "/admin",
      "/admin/attendance/live",
      "/admin/payroll/runs",
      "/admin/audit",
    ]) {
      expect(paths).toContain(required);
    }
  });
});
